### ISSUE TITLE
Senior Systems Analyst (Huntsville)

### ISSUE THREAD

**Issue by RocketCityHR** [tech256/jobs#93] opened 2017-09-28 21:49 UTC
Senior Systems Analyst

 

 

Company Overview:

KODA was founded on six decades of weapon system development experience from hands-on engineering to executive leadership. We have been the customer directly responsible for solving complex problems and developing highly technical products, and we delivered time after time. From designing radar systems to leading large-scale flight tests to managing international programs, we have a unique understanding of customer needs, deep domain expertise and proven technical skills. Our senior government decision-maker perspective, understanding of government organizations and experience integrating large multi-disciplinary teams make us distinctly qualified in our field.

 

Key Responsibilities:

    Conduct performance analysis and requirements analysis on a major weapon development program.
    Develop, update, and integrate delivery of analysis tools for testing and benchmarking.
    Develop planning documentation.
    Perform requirements analysis and develop technical performance measures definition, analysis, and reports.
    Develop Systems Analysis Plan. 
    Perform analysis of threat capability, performance, and feasibility.
    Participate in technical analysis meetings and reviews. 

 

Qualifications:

Education Requirements

B.S. in Engineering (or related discipline) and 15 years related experience

                                                 OR

M.S. in Engineering (or related discipline) and 10 years related experience

 

Experience:

    12+ years experience in weapon system development and analysis that supports responsibilities as described above.
    Proficiency with weapon system data analysis and analysis tool development.
    Exceptional work history. Demonstrated ability to work independently from high-level guidance.
    Exceptional communication skills.
    Proficiency in MS Office skills.

 

U.S. Citizenship is required

Must be able to obtain or have a Secret Security Clearance (Top Secret is preferred)

 

Location:

Based in Huntsville, Alabama

Customers:

Missile Defense Agency, Ground-based Midcourse Defense Program

 

KODA Technologies offers a comprehensive benefits package. Applicants are considered for all positions without regard to race, color, religion, sex, national origin, age, marital status, veteran status, sexual orientation, gender identity, or the presence of a non-job related medical condition or disability. KODA Technologies is an Equal Opportunity / Affirmative Action Employer. Contact us at human.resources@kodatech.com

KODA participates in the E-Verify program.

Note: When e-mailing your response, indicate job requisition #103-17 on your resume

 

For more information, or to apply now, you must go to the website below. Please DO NOT email your resume to us as we only accept applications through our website.

https://www.applicantpro.com/j/644946-194482

**Comment by iamvery** [comment] 2017-10-01 03:10
Closing, this appears to be a duplicate of #92

**Closed by iamvery** 2017-10-01 03:10 UTC
Labels: Develop, Hiring
